# Generated by Django 5.1.1 on 2024-09-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('exercises', models.CharField(max_length=1000)),
                ('days', models.CharField(max_length=7)),
                ('sets_per_exercise', models.CharField(max_length=100)),
                ('reps', models.CharField(max_length=300)),
                ('weight', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.CharField(max_length=1000)),
                ('days', models.CharField(max_length=7)),
                ('sets_per_exercise', models.CharField(max_length=100)),
                ('rep_range', models.CharField(max_length=10)),
                ('progression', models.CharField(max_length=15)),
            ],
        ),
    ]
